# -*- coding: utf-8 -*-
"""PROJECT CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FSaMG-6PXu4ta_ju8qYg1abKQ-ghNsxu
"""

# Headless runner for the testing notebooks
# - Executes either Project_files/500_Testing.ipynb or 2000_Testing.ipynb
# - Mocks tkinter to avoid GUI blocking
# - Uses a sample image from Dataset by default

import nbformat
import sys
import os
import types
import argparse
import datetime
import json
import numpy as np
import cv2

HERE = os.path.dirname(__file__)
PROJECT_FILES = os.path.join(HERE, 'Project_files')

# Simple fake tkinter and ttk to prevent GUI blocking
class DummyWidget:
    def __init__(self, *a, **k):
        self._store = {}
    def pack(self, *a, **k):
        pass
    def place(self, *a, **k):
        pass
    def grid(self, *a, **k):
        pass
    def config(self, *a, **k):
        pass
    def destroy(self, *a, **k):
        pass
    def update_idletasks(self, *a, **k):
        pass
    def mainloop(self, *a, **k):
        pass
    def winfo_screenwidth(self):
        return 1200
    def winfo_screenheight(self):
        return 800
    def geometry(self, *a, **k):
        pass
    def title(self, *a, **k):
        pass
    def resizable(self, *a, **k):
        pass
    def __setitem__(self, k, v):
        self._store[k] = v
    def __getitem__(self, k):
        return self._store.get(k, 0)

# Put fake tkinter in sys.modules so "from tkinter import *" works
fake_tk = types.SimpleNamespace()
for name in ('Frame','Label','Button','Tk','PhotoImage'):
    setattr(fake_tk, name, DummyWidget)
fake_tk.GROOVE = None
fake_tk.DISABLED = None
fake_tk.HORIZONTAL = 'horizontal'
fake_tk.VERTICAL = 'vertical'

fake_ttk = types.SimpleNamespace()
setattr(fake_ttk, 'Progressbar', DummyWidget)
setattr(fake_ttk, 'HORIZONTAL', 'horizontal')

sys.modules['tkinter'] = fake_tk
sys.modules['tkinter.ttk'] = fake_ttk

# Function to execute notebook cells in order inside a context dict

def exec_notebook(nb_path, context, timeout=600):
    nb = nbformat.read(nb_path, as_version=4)
    for cell in nb.cells:
        if cell.cell_type == 'code':
            src = cell.source
            # Skip IPython magic lines that won't run in plain exec
            lines = []
            for line in src.splitlines():
                if line.strip().startswith('%'):
                    # handle simple %store -r or %store -z or %store result_list
                    # skip magics
                    continue
                lines.append(line)
            code = "\n".join(lines)
            try:
                exec(compile(code, nb_path, 'exec'), context)
            except Exception as e:
                print(f"Error executing a cell in {os.path.basename(nb_path)}:\n", e)
                raise
    return context


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--denom', choices=('500','2000'), default='500', help='Denomination to test')
    parser.add_argument('--image', help='Path to input image (relative to Project_files or absolute)')
    parser.add_argument('--save-output', action='store_true', help='Save result images and summary into outputs/<denom>_<timestamp>/')
    parser.add_argument('--all', action='store_true', help='Run both denominations sequentially')
    args = parser.parse_args()

    def run_one(denom):
        nb_name = '500_Testing.ipynb' if denom == '500' else '2000_Testing.ipynb'
        nb_path = os.path.join(PROJECT_FILES, nb_name)

        if args.image:
            if os.path.isabs(args.image):
                img_path = args.image
            else:
                img_path = os.path.join(PROJECT_FILES, args.image)
        else:
            # Default sample image bundled in dataset
            img_rel = 'Dataset\\500_dataset\\500_s1.jpg' if denom == '500' else 'Dataset\\2000_dataset\\2000_s1.jpg'
            img_path = os.path.join(PROJECT_FILES, img_rel)

        if not os.path.exists(img_path):
            print('ERROR: image not found:', img_path)
            return None

        # Execution context where notebook code will run
        ctx = {
            '__name__': '__main__',
            'path': img_path,  # many notebooks expect variable 'path' to be set (via %store -r path)
        }

        print('Running', nb_name)
        exec_notebook(nb_path, ctx)

        # Optionally save outputs
        out_dir = None
        if args.save_output:
            t = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
            out_dir = os.path.join(HERE, 'outputs', f'{denom}_{t}')
            os.makedirs(out_dir, exist_ok=True)

        # After execution, try to print a summary from result_list if present
        if 'result_list' in ctx:
            rl = ctx['result_list']
            print('\n--- Result summary ---')
            summary_records = []
            for i, item in enumerate(rl, start=1):
                # attempt to find numpy arrays/images inside item
                imgs = []
                vals = []
                if isinstance(item, list):
                    for v in item:
                        if isinstance(v, np.ndarray):
                            imgs.append(v)
                        else:
                            vals.append(v)
                else:
                    if isinstance(item, np.ndarray):
                        imgs.append(item)
                    else:
                        vals.append(item)

                # Save first image if requested
                if out_dir and imgs:
                    fname = os.path.join(out_dir, f'feature_{i}.png')
                    try:
                        cv2.imwrite(fname, imgs[0])
                    except Exception as e:
                        print('Failed to write image for feature', i, e)

                # Print compact summary
                rec = {'feature': i, 'values': [str(x) for x in vals][:4]}
                summary_records.append(rec)
                print(f'Feature {i}:', ', '.join(rec['values']))

            # save JSON summary
            if out_dir:
                with open(os.path.join(out_dir, 'summary.json'), 'w', encoding='utf-8') as f:
                    json.dump(summary_records, f, indent=2)
        else:
            print('No result_list found in executed notebook context.')

        return out_dir

    # If --all run both sequentially
    if args.all:
        out1 = run_one('500')
        out2 = run_one('2000')
        print('\nOutputs saved to:')
        if out1: print(out1)
        if out2: print(out2)
        return

    # default single run
    out = run_one(args.denom)
    if out:
        print('\nSaved outputs to:', out)

if __name__ == '__main__':
    main()